Add patch remove feature
CABLE-LSM/benchcab pull request #125
Opened 2023-08-08 01:23 UTC by SeanBryan51

Currently, `benchcab` does not support removing namelist parameters from the base namelist file. For example, legacy CABLE branches may not be compatible with a namelist parameter in the base namelist file.

This change adds a `patch_remove` key which will remove a given set of namelist parameters for a specific branch.

Fixes #92

2023-08-08 02:25 UTC, SeanBryan51 commented
# Integration tests
## Test patch remove feature:
```
#!/bin/bash
bench_example_dir='bench_example_test_patch_remove'
rm -rf $bench_example_dir
git clone git@github.com:CABLE-LSM/bench_example.git $bench_example_dir
cd $bench_example_dir
git reset --hard 6287539e96fc8ef36dc578201fbf9847314147fb
cat > config.yaml << EOL
project: tm70

experiment: AU-Tum

realisations: [
  {
    path: "trunk",
  },
  {
    path: "branches/Users/mm3972/CABLE_GW_into_trunk_version2",
    revision: 9571,
    build_script: offline/build.ksh,
    patch_remove: {
      cable: {
        soilparmnew: nil
      }
    }
  }
]

modules: [
  intel-compiler/2021.1.1,
  netcdf/4.7.4,
  openmpi/4.1.0
]

science_configurations:
  - cable:
      cable_user:
        CONSISTENCY_CHECK: False
EOL
benchcab run -v
```
Job standard output:
```
Running fluxsite tasks...
Running task AU-Tum_2002-2017_OzFlux_Met_R1_S0... CABLE standard output saved in /scratch/tm70/sb8430/benchcab_integration_tests/bench_example_test_patch_remove/runs/fluxsite/tasks/AU-Tum_2002-2017_OzFlux_Met_R1_S0/out.txt
./cable cable.nml
Adding attributes to output file: /scratch/tm70/sb8430/benchcab_integration_tests/bench_example_test_patch_remove/runs/fluxsite/outputs/AU-Tum_2002-2017_OzFlux_Met_R1_S0_out.nc
Running task AU-Tum_2002-2017_OzFlux_Met_R0_S0... CABLE standard output saved in /scratch/tm70/sb8430/benchcab_integration_tests/bench_example_test_patch_remove/runs/fluxsite/tasks/AU-Tum_2002-2017_OzFlux_Met_R0_S0/out.txt
./cable cable.nml
Adding attributes to output file: /scratch/tm70/sb8430/benchcab_integration_tests/bench_example_test_patch_remove/runs/fluxsite/outputs/AU-Tum_2002-2017_OzFlux_Met_R0_S0_out.nc
Successfully ran fluxsite tasks

Running comparison tasks...
Comparing files AU-Tum_2002-2017_OzFlux_Met_R0_S0_out.nc and AU-Tum_2002-2017_OzFlux_Met_R1_S0_out.nc bitwise...
nccmp -df /scratch/tm70/sb8430/benchcab_integration_tests/bench_example_test_patch_remove/runs/fluxsite/outputs/AU-Tum_2002-2017_OzFlux_Met_R0_S0_out.nc /scratch/tm70/sb8430/benchcab_integration_tests/bench_example_test_patch_remove/runs/fluxsite/outputs/AU-Tum_2002-2017_OzFlux_Met_R1_S0_out.nc
Failure: files AU-Tum_2002-2017_OzFlux_Met_R0_S0_out.nc AU-Tum_2002-2017_OzFlux_Met_R1_S0_out.nc differ. Results of diff have been written to /scratch/tm70/sb8430/benchcab_integration_tests/bench_example_test_patch_remove/runs/fluxsite/analysis/bitwise-comparisons/AU-Tum_2002-2017_OzFlux_Met_S0_R0_R1.txt
Successfully ran comparison tasks

======================================================================================
                  Resource Usage on 2023-08-08 12:14:45:
   Job Id:             92172069.gadi-pbs
   Project:            tm70
   Exit Status:        0
   Service Units:      1.18
   NCPUs Requested:    18                     NCPUs Used: 18              
                                           CPU Time Used: 00:03:13        
   Memory Requested:   30.0GB                Memory Used: 1.72GB          
   Walltime requested: 06:00:00            Walltime Used: 00:01:58        
   JobFS requested:    100.0MB                JobFS used: 0B              
======================================================================================
```

2023-08-10 07:08 UTC, ccarouge requested changes
It is good but the documentation needs some clarifying.

2023-08-10 07:08 UTC, ccarouge commented on docs/user_guide/config_options.md
> +: Specifies branch-specific namelist settings to be removed from the `cable.nml` namelist settings. The `patch_remove` key is similar to [`patch`](#`patch`) in the that these settings will be removed
> The `patch_remove` key is similar to [`patch`](#`patch`) ...

I don't understand this bit. Are you trying to say they are the opposite of each other?

2023-08-10 07:08 UTC, ccarouge commented on docs/user_guide/config_options.md
> +: The `patch_remove` key must be a dictionary like data structure that is compliant with the [`f90nml`][f90nml-github] python package.
```suggestion
: The `patch_remove` key must be a dictionary-like data structure that is compliant with the [`f90nml`][f90nml-github] python package.
```

In this case, the value for the namelist option is unused. Should we add some details here about that and that the value can be set to anything, only the key matters?

2023-08-15 06:28 UTC, ccarouge approved these changes

2023-08-15 07:19 UTC, merged