Remove tests on standard output
CABLE-LSM/benchcab pull request #222
Opened 2023-12-19 23:12 UTC by SeanBryan51

This change removes any assertions on standard output from the tests so that tests focus on testing functionality (where possible) rather than the messages (print statements) that are emitted from the tested functions.

Fixes #221

2023-12-19 23:54 UTC, bschroeter requested changes
OK so the tests have been removed - thanks. But did we want to look at reimplementing them with subprocess-mock? Or update to test end-to-end (i.e. existence of files etc.) rather than on stdout?

2023-12-20 00:24 UTC, SeanBryan51 commented
I'm happy to switch to subprocess-mock in our unit testing however this might be better to do in a separate PR. Is this what you are suggesting?

2023-12-20 01:05 UTC, bschroeter commented
> I'm happy to switch to subprocess-mock in our unit testing however this might be better to do in a separate PR. Is this what you are suggesting?

That makes sense. Let's just accept that coverage will go down, but we should raise another issue to re-engineer these tests to ensure that we're covered for the functionality going forward.

2023-12-20 01:06 UTC, bschroeter approved these changes

2023-12-20 01:23 UTC, SeanBryan51 commented
Also just to clarify, is subprocess-mock referring to the [pytest-subprocess](https://github.com/aklajnert/pytest-subprocess) pytest plugin that you have been working with?

2023-12-20 01:23 UTC, merged