Add branch specific namelist settings
CABLE-LSM/benchcab pull request #43
Opened 2023-03-20 01:26 UTC by SeanBryan51

This change allows for users to add branch specific namelist settings in the config file that get "patched" to the base namelist settings used for both branches. These additional settings are set by specifying an optional `patch` key in each realisation. Currently, this change supports the ability to add a `patch` to both realisations.

Addresses issue https://github.com/CABLE-LSM/benchcab/issues/29

2023-03-20 04:56 UTC, SeanBryan51 commented
@ccarouge I've linked issue #29 so that this PR will close the issue. I know a lot of the discussion was about what we do with the model output, but if there were any other requirements for the issue that I have forgotten to add please let me know

2023-03-22 03:09 UTC, ccarouge requested changes
One comment but with impact on a few parts of the code and the tests.

2023-03-22 05:13 UTC, SeanBryan51 commented on benchcab/task.py
> +            self.patch_namelist_file({'cable': self.branch_patch}, root_dir=root_dir)
Yes I think having to include `{'cable': {......}}` in the patch is a good idea. Should we do the same for the science configurations for consistency? For example, in the [site_configs.yaml](https://github.com/CABLE-LSM/bench_example/blob/main/site_configs.yaml)
```yaml
sci0: {
    cable_user: {
        GS_SWITCH: "medlyn",
        FWSOIL_SWITCH: "Haverd2013"
    }
}
```
would become
```yaml
sci0: {
    cable: {
        cable_user: {
            GS_SWITCH: "medlyn",
            FWSOIL_SWITCH: "Haverd2013"
        }
    }
}
```

2023-03-24 01:04 UTC, ccarouge commented on benchcab/task.py
> +            self.patch_namelist_file({'cable': self.branch_patch}, root_dir=root_dir)
Indeed we need the same in the science configurations.

2023-03-26 05:57 UTC, SeanBryan51 commented on benchcab/task.py
> +            self.patch_namelist_file({'cable': self.branch_patch}, root_dir=root_dir)
I have made the changes for the `patch` key: see [2006d9c](https://github.com/CABLE-LSM/benchcab/pull/43/commits/2006d9cfe261caa36cd58373d8567ea48f3bc590). I have added a separate issue for the changes for science configurations (see https://github.com/CABLE-LSM/benchcab/issues/46) as I prefer to make these changes once this PR and #44 are merged in.

2023-03-27 05:41 UTC, ccarouge approved these changes

2023-03-27 05:41 UTC, merged