Polish standard output messages
CABLE-LSM/benchcab pull request #69
Opened 2023-05-02 00:01 UTC by SeanBryan51

Currently, `benchcab` outputs stdout from other commands such as `svn` and `./build3.sh`, but does not output anything when running `./cable` or when generating particular directory structures.

This commit improves the messages output to stdout by `benchcab` for all sub-commands. We also add a boolean flag to specify verbose output for each sub-command.

Write the standard output from CABLE to the `tasks/<task_name>/out.txt` directory instead of writing to `/dev/null` so that it is accessible to the user.

Remove `wd9` dependence in source code.

Fixes #67 and #64

2023-05-03 00:49 UTC, SeanBryan51 commented
Standard output from `benchcab run`:
```
$ benchcab run
Creating src directory: /scratch/tm70/sb8430/bench_example/src
Checking out repositories...
Successfully checked out trunk at revision 9550
Successfully checked out test-branch at revision 9550
Successfully checked out CABLE-AUX at revision 9550
Writing revision number info to rev_number-1.log
Compiling CABLE serially for realisation trunk...
Successfully compiled CABLE for realisation trunk
Compiling CABLE serially for realisation test-branch...
Successfully compiled CABLE for realisation test-branch
Setting up run directory tree for FLUXNET tests...
Creating runs/site/logs directory: /scratch/tm70/sb8430/bench_example/runs/site/logs
Creating runs/site/outputs directory: /scratch/tm70/sb8430/bench_example/runs/site/outputs
Creating runs/site/tasks directory: /scratch/tm70/sb8430/bench_example/runs/site/tasks
Creating task directories...
Setting up tasks...
Successfully setup FLUXNET tasks
Creating PBS job script to run FLUXNET tasks on compute nodes: benchmark_cable_qsub.sh
PBS job submitted: 82479088.gadi-pbs
The CABLE log file for each task is written to runs/site/logs/<task_name>_log.txt
The CABLE standard output for each task is written to runs/site/tasks/<task_name>/out.txt
The NetCDF output for each task is written to runs/site/outputs/<task_name>_out.nc
```
Captured stdout from job:
```
Running FLUXNET tasks...
Successfully ran FLUXNET tasks
```

2023-05-03 01:05 UTC, SeanBryan51 commented
Standard out from `benchcab run -v` (verbose):
```
$ benchcab run -v
Creating src directory: /scratch/tm70/sb8430/bench_example/src
Checking out repositories...
svn checkout https://trac.nci.org.au/svn/cable/trunk /scratch/tm70/sb8430/bench_example/src/trunk
A    src/trunk/offline
A    src/trunk/offline/cable_pft_params.F90
A    src/trunk/offline/.Hytiallia.sumbal
A    src/trunk/offline/pft_params.nml
A    src/trunk/offline/cable_input.F90
A    src/trunk/offline/TumbaFluxnet.1.3_met.nc
A    src/trunk/offline/cable_checks.F90
A    src/trunk/offline/cable_mpidrv.F90
A    src/trunk/offline/cable_parameters.F90
A    src/trunk/offline/.GSWP2.log_cable
A    src/trunk/offline/cable_site.F90
A    src/trunk/offline/gridinfo_CSIRO_1x1.nc
A    src/trunk/offline/cable_metutils.F90
A    src/trunk/offline/cbl_model_driver_offline.F90
A    src/trunk/offline/casa_cable.F90
A    src/trunk/offline/cable_abort.F90
A    src/trunk/offline/cable.nml
A    src/trunk/offline/build3.sh
A    src/trunk/offline/cable_soil_params.F90
A    src/trunk/offline/file.txt
A    src/trunk/offline/cable_define_types.F90
A    src/trunk/offline/cable_cru_TRENDY.F90
A    src/trunk/offline/cable_mpiworker.F90
A    src/trunk/offline/landuse_inout.F90
A    src/trunk/offline/.Tumba.sumbal
A    src/trunk/offline/CASAONLY_LUC.F90
A    src/trunk/offline/cable_plume_mip.F90
A    src/trunk/offline/cable_write.F90
A    src/trunk/offline/cable_initialise.F90
A    src/trunk/offline/pftlookup.csv
A    src/trunk/offline/cable_namelist_input.F90
A    src/trunk/offline/cable_mpicommon.F90
A    src/trunk/offline/parallel_cable
A    src/trunk/offline/cable_output.F90
A    src/trunk/offline/.Ampero.sumbal
A    src/trunk/offline/cable_mpimaster.F90
A    src/trunk/offline/casa_offline_inout.F90
A    src/trunk/offline/cable_iovars.F90
A    src/trunk/offline/cable_phenology.F90
A    src/trunk/offline/run.ksh
A    src/trunk/offline/cable_weathergenerator.F90
A    src/trunk/offline/CSIRO_BSD_MIT_License_v2.0_CABLE.txt
A    src/trunk/offline/cable_read.F90
A    src/trunk/offline/casa_ncdf.F90
A    src/trunk/offline/spincasacnp.F90
A    src/trunk/offline/cable_soilparm.nml
A    src/trunk/offline/serial_cable
A    src/trunk/offline/cable_LUC_EXPT.F90
A    src/trunk/offline/Makefile
A    src/trunk/offline/cable_driver.F90
A    src/trunk/params
A    src/trunk/params/cable_other_constants_mod.F90
A    src/trunk/params/cable_phys_constants_mod.F90
A    src/trunk/params/cable_params_mod.F90
A    src/trunk/params/cable_photo_constants_mod.F90
A    src/trunk/params/cable_maths_constants_mod.F90
A    src/trunk/params/grid_constants_cbl.F90
A    src/trunk/science
A    src/trunk/science/casa-cnp
A    src/trunk/science/casa-cnp/casa_feedback.F90
A    src/trunk/science/casa-cnp/casa_phenology.F90
A    src/trunk/science/casa-cnp/casa_dimension.F90
A    src/trunk/science/casa-cnp/casa_variable.F90
A    src/trunk/science/casa-cnp/casa_sumcflux.F90
A    src/trunk/science/casa-cnp/casa_readbiome.F90
A    src/trunk/science/casa-cnp/casa_inout.F90
A    src/trunk/science/casa-cnp/bgcdriver.F90
A    src/trunk/science/casa-cnp/casa_cnp.F90
A    src/trunk/science/casa-cnp/casa_param.F90
A    src/trunk/science/casa-cnp/casa_rplant.F90
A    src/trunk/science/casa-cnp/biogeochem_casa.F90
A    src/trunk/science/albedo
A    src/trunk/science/albedo/cbl_albedo.F90
A    src/trunk/science/albedo/cbl_snow_albedo.F90
A    src/trunk/science/albedo/cbl_soilColour_albedo.F90
A    src/trunk/science/sli
A    src/trunk/science/sli/cable_sli_utils.F90
A    src/trunk/science/sli/cable_sli_main.F90
A    src/trunk/science/sli/cable_sli_roots.F90
A    src/trunk/science/sli/cable_sli_solve.F90
A    src/trunk/science/sli/cable_sli_numbers.F90
A    src/trunk/science/canopy
A    src/trunk/science/canopy/cbl_SurfaceWetness.F90
A    src/trunk/science/canopy/cbl_friction_vel.F90
A    src/trunk/science/canopy/cbl_fwsoil.F90
A    src/trunk/science/canopy/cbl_photosynthesis.F90
A    src/trunk/science/canopy/cbl_pot_evap_snow.F90
A    src/trunk/science/canopy/cbl_zetar.F90
A    src/trunk/science/canopy/cbl_LAI_canopy_height.F90
A    src/trunk/science/canopy/cbl_dryLeaf.F90
A    src/trunk/science/canopy/cbl_wetleaf.F90
A    src/trunk/science/canopy/cbl_latent_heat.F90
A    src/trunk/science/canopy/cbl_qsat.F90
A    src/trunk/science/canopy/cbl_within_canopy.F90
A    src/trunk/science/canopy/cable_canopy.F90
A    src/trunk/science/radiation
A    src/trunk/science/radiation/cbl_radiation.F90
A    src/trunk/science/radiation/cbl_spitter.F90
A    src/trunk/science/radiation/cbl_init_radiation.F90
A    src/trunk/science/radiation/cbl_rhoch.F90
A    src/trunk/science/radiation/cbl_sinbet.F90
A    src/trunk/science/landuse
A    src/trunk/science/landuse/landuse3.F90
A    src/trunk/science/landuse/landuse_constant.F90
A    src/trunk/science/misc
A    src/trunk/science/misc/cable_carbon.F90
A    src/trunk/science/misc/cable_air.F90
A    src/trunk/science/misc/cable_climate.F90
A    src/trunk/science/roughness
A    src/trunk/science/roughness/cable_roughness.F90
A    src/trunk/science/roughness/roughnessHGT_effLAI_cbl.F90
A    src/trunk/science/soilsnow
A    src/trunk/science/soilsnow/cbl_soilsnow_data.F90
A    src/trunk/science/soilsnow/cbl_soilfreeze.F90
A    src/trunk/science/soilsnow/cbl_surfbv.F90
A    src/trunk/science/soilsnow/cbl_snowMelt.F90
A    src/trunk/science/soilsnow/cbl_snowl_adjust.F90
A    src/trunk/science/soilsnow/cbl_trimb.F90
A    src/trunk/science/soilsnow/cbl_GW.F90
A    src/trunk/science/soilsnow/cbl_stempv.F90
A    src/trunk/science/soilsnow/cbl_smoisturev.F90
A    src/trunk/science/soilsnow/cbl_soilsnow_main.F90
A    src/trunk/science/soilsnow/cbl_Oldconductivity.F90
A    src/trunk/science/soilsnow/cbl_conductivity.F90
A    src/trunk/science/soilsnow/cbl_snowCheck.F90
A    src/trunk/science/soilsnow/cbl_snowDensity.F90
A    src/trunk/science/soilsnow/cbl_hyd_redistrib.F90
A    src/trunk/science/soilsnow/cbl_snow_aging.F90
A    src/trunk/science/soilsnow/cbl_thermal.F90
A    src/trunk/science/soilsnow/cbl_snowAccum.F90
A    src/trunk/science/soilsnow/cbl_soilsnow_init_special.F90
A    src/trunk/science/soilsnow/cbl_remove_trans.F90
A    src/trunk/science/pop
A    src/trunk/science/pop/pop_def.F90
A    src/trunk/science/pop/POP.F90
A    src/trunk/science/pop/POPLUC.F90
A    src/trunk/science/pop/pop_types.F90
A    src/trunk/science/pop/pop_mpi.F90
A    src/trunk/science/pop/pop_io.F90
A    src/trunk/science/pop/pop_constants.F90
A    src/trunk/science/gw_hydro
A    src/trunk/science/gw_hydro/cable_psm.F90
A    src/trunk/science/gw_hydro/cable_gw_hydro.F90
A    src/trunk/coupled
A    src/trunk/coupled/JAC
A    src/trunk/coupled/JAC/map_veg_parameters_cbl.F90
A    src/trunk/coupled/JAC/control
A    src/trunk/coupled/JAC/control/util
A    src/trunk/coupled/JAC/control/util/pack_mod_cbl.F90
A    src/trunk/coupled/JAC/control/util/activeTile_mask_cbl.F90
A    src/trunk/coupled/JAC/control/interface
A    src/trunk/coupled/JAC/control/interface/radiation
A    src/trunk/coupled/JAC/control/interface/radiation/rad_driver_cbl.F90
A    src/trunk/coupled/JAC/control/interface/radiation/rad_unpack_cbl.F90
A    src/trunk/coupled/JAC/control/cable_land
A    src/trunk/coupled/JAC/control/cable_land/radiation
A    src/trunk/coupled/JAC/control/cable_land/radiation/cable_land_albedo_mod_cbl.F90
A    src/trunk/coupled/JAC/control/cable_land/radiation/alloc_rad_albedo_vars_cbl.F90
A    src/trunk/coupled/JAC/control/cable
A    src/trunk/coupled/JAC/control/cable/shared
A    src/trunk/coupled/JAC/control/cable/shared/progs_cbl_vars_mod.F90
A    src/trunk/coupled/JAC/control/cable/shared/params_io_cbl.F90
A    src/trunk/coupled/JAC/control/cable/shared/work_vars_mod_cbl.F90
A    src/trunk/coupled/JAC/control/cable/shared/cable_surface_types_mod.F90
A    src/trunk/coupled/JAC/control/cable/standalone
A    src/trunk/coupled/JAC/control/cable/standalone/cable_fields_mod.F90
A    src/trunk/coupled/JAC/control/shared
A    src/trunk/coupled/JAC/control/shared/cable_surface_types_mod.F90 [...]

2023-05-05 02:16 UTC, ccarouge commented
I've noticed this output in the build part:

```
Compiling CABLE serially for realisation trunk...
./my_build.ksh

Building cable (serial)

ERROR: Multiple (2) conda environments have been loaded, cannot unload with module
ERROR: Try 'conda deactivate' first

Unloading conda/analysis3-22.10
  ERROR: Module evaluation aborted

Build setup complete.
Compiling now ...
```
Do you know where it comes from? I don't see it happening for me. Just checking it is due to your setup and not a problem for users.

2023-05-05 04:01 UTC, SeanBryan51 commented
I think the error message is due to a custom conda environment being activated and so we cannot `module unload conda` until we run `conda deactivate` (I currently use a custom conda environment for testing benchcab). When the error occurs, the conda module remains loaded. I don't think I have had any issues with this so far.

2023-05-10 23:28 UTC, ccarouge requested changes

2023-05-10 23:28 UTC, ccarouge commented on benchcab/job_script.py
> +#PBS -l storage=gdata/ks32+gdata/wd9+gdata/hh5+gdata/{project}+{curdir_root}/{curdir_proj}
```suggestion
#PBS -l storage=gdata/ks32+gdata/hh5+gdata/{project}+{curdir_root}/{curdir_proj}
```
Remove `wd9` now if we change the formatting here

2023-05-15 01:52 UTC, ccarouge approved these changes

2023-05-16 05:51 UTC, ccarouge commented
- [ ] add indentation to verbose output within running a task
- [ ] blank line between steps of the workflow in all cases (verbose True/False)

2023-05-17 06:09 UTC, merged