Fix compilation with custom script
CABLE-LSM/benchcab pull request #71
Opened 2023-05-03 01:16 UTC by ccarouge

This is a quick fix for the case a custom script is provided. It fixes the issue that the `mpi` option might not work in the same way for the custom script as for the default build.

Considering the build code is likely to change further, the fix is applied in a simple way that might be revisited later on.

2023-05-03 01:39 UTC, SeanBryan51 requested changes
Looks good to me. My only comment is that this change breaks the [test_build.py](https://github.com/CABLE-LSM/benchcab/blob/fix-build/tests/test_build.py) tests you wrote. Should we remove unit testing for the build stuff? Writing tests for this part of the code is hard since it is very dependent on the environment (commands need to be run on Gadi)

2023-05-03 04:13 UTC, ccarouge commented
Ah yes absolutely. I knew I was forgetting something. We really need to put the tests in an Action. I'll get to that.

2023-05-04 23:57 UTC, ccarouge commented
I removed the invalid tests. I tested the code with a `config.yaml` file with a realisation using the default build script and one with the build script specified. Both source codes were built as intended.

2023-05-05 00:16 UTC, SeanBryan51 approved these changes

2023-05-05 01:26 UTC, merged