Add ability to use branches of other users
CABLE-LSM/benchcab pull request #82
Opened 2023-05-18 00:58 UTC by SeanBryan51

The user should be able to checkout branches of other users so that test suites can be reproduced by any user.

This change lets the user specify the path relative to the SVN root of the CABLE repository for each branch by specifying the `path` key in the configuration file. Remove the `trunk` and `share_branch` keys from the configuration file as this information is contained within `path`.

This change repurposes the `name` key for each branch to be an alias used internally by benchcab. This lets the user specify the directory name when checking out the branch, that is, `name` is the optional `PATH` argument to svn checkout`. This is useful in the case that we have a collision in branch names when checking out multiple branches.

Remove the `-M` PBS argument for sending emails in the job script as the default behaviour is sufficient.

Remove the `user` key as this is now redundant.

Update unit tests for `check_config()`.

Fixes #61

2023-05-18 23:53 UTC, SeanBryan51 commented
**TODO**

- [ ] If we are repurposing the `name` key in the configuration file to be an alias. This should be an optional key. By default we should use the base name of the `path` key.

2023-05-18 23:59 UTC, ccarouge requested changes
That's good. But you forgot to update the documentation.

2023-05-18 23:59 UTC, ccarouge commented on benchcab/job_script.py
> -#PBS -M {email_address}
Instead should we have:
```
#PBS -m e
```
This will send an email at completion of the script whether it succeeds or fails.

2023-05-19 00:01 UTC, ccarouge commented
Do we want to make `name` optional? And use the stem of path if not provided?

2023-05-25 23:50 UTC, ccarouge approved these changes

2023-05-31 02:30 UTC, merged